# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/finger/Desktop/mycpu3/mycpu3.cache/wt [current_project]
set_property parent.project_path C:/Users/finger/Desktop/mycpu3/mycpu3.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/finger/Desktop/mycpu3/mycpu3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/finger/Desktop/mycpu3/mycpu3.srcs/sources_1/ip/prgrom/inst_ram.coe
add_files -quiet C:/Users/finger/Desktop/2021/download_test/synthesized_ip/dram/dram.dcp
set_property used_in_implementation false [get_files C:/Users/finger/Desktop/2021/download_test/synthesized_ip/dram/dram.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/finger/Desktop/dummy_cpu_trace/ALU.v
  C:/Users/finger/Desktop/mycpu3/mycpu3.srcs/sources_1/new/BUS.v
  C:/Users/finger/Desktop/dummy_cpu_trace/CPU.v
  C:/Users/finger/Desktop/dummy_cpu_trace/CTRL.v
  C:/Users/finger/Desktop/dummy_cpu_trace/DRAM.v
  C:/Users/finger/Desktop/dummy_cpu_trace/NPC.v
  C:/Users/finger/Desktop/dummy_cpu_trace/PC.v
  C:/Users/finger/Desktop/dummy_cpu_trace/RF.v
  C:/Users/finger/Desktop/dummy_cpu_trace/SEXT.v
  C:/Users/finger/Desktop/dummy_cpu_trace/result_display.v
  C:/Users/finger/Desktop/mycpu3/mycpu3.srcs/sources_1/new/cpu_top.v
}
read_ip -quiet C:/Users/finger/Desktop/mycpu3/mycpu3.srcs/sources_1/ip/cpuclk/cpuclk.xci
set_property used_in_implementation false [get_files -all c:/Users/finger/Desktop/mycpu3/mycpu3.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/finger/Desktop/mycpu3/mycpu3.srcs/sources_1/ip/cpuclk/cpuclk.xdc]
set_property used_in_implementation false [get_files -all c:/Users/finger/Desktop/mycpu3/mycpu3.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc]

read_ip -quiet c:/Users/finger/Desktop/mycpu3/mycpu3.srcs/sources_1/ip/prgrom/prgrom.xci
set_property used_in_implementation false [get_files -all c:/Users/finger/Desktop/mycpu3/mycpu3.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/finger/Desktop/pin.xdc
set_property used_in_implementation false [get_files C:/Users/finger/Desktop/pin.xdc]

read_xdc C:/Users/finger/Desktop/mycpu3/mycpu3.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files C:/Users/finger/Desktop/mycpu3/mycpu3.srcs/constrs_1/new/clock.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cpu_top -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_top_utilization_synth.rpt -pb cpu_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
